In [1]:
# importing libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
waves = pd.read_csv('/Users/rubyestrickland/Desktop/EnvDataSci/HW08/Waves_2023.txt', sep=r'\s+')

In [3]:
waves.describe()

,YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
count,17285.0,17285.000000,17285.000000,17285.000000,17285.000000,17285.0,17285.0,17285.0,17285.000000,17285.000000,17285.000000,17285.000000,17285.0,17285.0,17285.000000,17285.0,17285.0,17285.0
mean,2023.0,6.526063,15.800579,11.499277,40.985594,999.0,99.0,99.0,1.083535,12.161879,6.813054,234.556205,9999.0,999.0,17.196535,999.0,99.0,99.0
std,0.0,3.467253,8.817920,6.925343,15.007646,0.0,0.0,0.0,2.296129,4.165737,2.803208,49.429981,0.0,0.0,2.564664,0.0,0.0,0.0
min,2023.0,1.000000,1.000000,0.000000,0.000000,999.0,99.0,99.0,0.330000,2.860000,3.420000,10.000000,9999.0,999.0,11.800000,999.0,99.0,99.0
25%,2023.0,4.000000,8.000000,5.000000,26.000000,999.0,99.0,99.0,0.730000,9.090000,5.500000,179.000000,9999.0,999.0,14.600000,999.0,99.0,99.0
50%,2023.0,6.000000,16.000000,11.000000,26.000000,999.0,99.0,99.0,0.880000,12.500000,6.360000,263.000000,9999.0,999.0,17.500000,999.0,99.0,99.0
75%,2023.0,10.000000,23.000000,18.000000,56.000000,999.0,99.0,99.0,1.140000,14.290000,7.550000,271.000000,9999.0,999.0,19.400000,999.0,99.0,99.0
max,2023.0,12.000000,31.000000,23.000000,56.000000,999.0,99.0,99.0,99.000000,99.000000,99.000000,999.000000,9999.0,999.0,23.900000,999.0,99.0,99.0

In [4]:
waves= waves.drop(['WDIR','WSPD','GST','PRES','ATMP','DEWP','VIS','TIDE'], axis=1)
waves.describe()

,YY,MM,DD,hh,mm,WVHT,DPD,APD,MWD,WTMP
count,17285.0,17285.000000,17285.000000,17285.000000,17285.000000,17285.000000,17285.000000,17285.000000,17285.000000,17285.000000
mean,2023.0,6.526063,15.800579,11.499277,40.985594,1.083535,12.161879,6.813054,234.556205,17.196535
std,0.0,3.467253,8.817920,6.925343,15.007646,2.296129,4.165737,2.803208,49.429981,2.564664
min,2023.0,1.000000,1.000000,0.000000,0.000000,0.330000,2.860000,3.420000,10.000000,11.800000
25%,2023.0,4.000000,8.000000,5.000000,26.000000,0.730000,9.090000,5.500000,179.000000,14.600000
50%,2023.0,6.000000,16.000000,11.000000,26.000000,0.880000,12.500000,6.360000,263.000000,17.500000
75%,2023.0,10.000000,23.000000,18.000000,56.000000,1.140000,14.290000,7.550000,271.000000,19.400000
max,2023.0,12.000000,31.000000,23.000000,56.000000,99.000000,99.000000,99.000000,999.000000,23.900000

In [5]:
# WVHT = Wave Height (m)
# DPD = Dominant wave period (seconds)
# APD = Average wave period (seconds)
# MWD = The direction from which the waves at the dominant period (DPD) are coming
# WTMP = Sea surface temperature (Celsius)

waves = waves[waves['WVHT'] < 99]
waves = waves[waves['DPD'] < 99]
waves = waves[waves['APD'] < 99]
waves = waves[waves['MWD'] < 999]

In [6]:
wavesML = waves.drop(['YY','MM','DD','hh','mm'],axis = 1)

In [7]:
wavesML

       WVHT    DPD    APD  MWD  WTMP
0      1.12  12.50   7.69  269  15.3
1      1.16  11.76   7.34  272  15.3
2      1.20  12.50   7.08  268  15.3
3      1.25  10.53   7.33  268  15.4
4      1.27  10.53   7.57  268  15.5
...     ...    ...    ...  ...   ...
17280  2.01  14.29  11.19  270  16.7
17281  1.75  15.38  10.37  267  16.7
17282  1.79  13.33  10.50  268  16.8
17283  1.66  14.29  10.32  271  16.8
17284  1.70  12.50  10.54  271  16.9

[17276 rows x 5 columns]

In [8]:
df_X = wavesML.drop(['WVHT'],axis=1).to_numpy()
df_y = wavesML['WVHT'].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size=0.10)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.10)

In [9]:
from sklearn.ensemble import RandomForestRegressor
regRF = RandomForestRegressor(n_estimators=100)
regRF = regRF.fit(X_train, y_train)
yPred = regRF.predict(X_val)
mean_squared_error(yPred,y_val)

0.0630732211319173

In [13]:
regRF = RandomForestRegressor(n_estimators=25)
regRF = regRF.fit(X_train, y_train)
yPred = regRF.predict(X_val)
val_mse = mean_squared_error(yPred,y_val)
print(val_mse)

0.0639596781818078

In [14]:
yPred_test = regRF.predict(X_test)
test_mse = mean_squared_error(yPred_test, y_test)
print(test_mse)

0.08137515851995884

In [15]:
yPred_train = regRF.predict(X_train)
train_mse = mean_squared_error(yPred_train, y_train)
print(train_mse)

0.012542747788308408

In [27]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    df_X, df_y, test_size=0.2, random_state=42)

In [29]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = Ridge(alpha=1.0)
model.fit(X_train_scaled, y_train)

Ridge()

In [35]:
y_pred_train = model.predict(X_train_scaled)
y_pred_test = model.predict(X_test_scaled)
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred_test)

In [36]:
print(train_mse)

0.19598029797873548

In [37]:
print(test_mse)

0.19438708189890555

In [38]:
X_val_scaled = scaler.transform(X_val)
y_pred_val = model.predict(X_val_scaled)
val_mse = mean_squared_error(y_val, y_pred_val)
print(val_mse)

0.16613009796272502

In [39]:
X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size=0.10)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.10)

In [41]:
regRF = RandomForestRegressor(n_estimators=25)
regRF = regRF.fit(X_train, y_train)
yPred = regRF.predict(X_val)
val_mse = mean_squared_error(yPred,y_val)
print(val_mse)

0.08015343440585923

In [42]:
yPred_test = regRF.predict(X_test)
test_mse = mean_squared_error(yPred_test, y_test)
print(test_mse)

0.07751686425226338

In [43]:
yPred_train = regRF.predict(X_train)
train_mse = mean_squared_error(yPred_train, y_train)
print(train_mse)

0.012420060936331658

In [50]:
tree_counts = [2, 10, 25, 50, 100, 250, 500, 1000]
results_data = []

for n_trees in tree_counts:
    rf_model = RandomForestRegressor(n_estimators=n_trees, random_state=42, n_jobs=-1)
    rf_model.fit(X_train, y_train)
    
    y_pred_train = rf_model.predict(X_train)
    y_pred_val = rf_model.predict(X_val)
    y_pred_test = rf_model.predict(X_test)
    
    train_mse = mean_squared_error(y_train, y_pred_train)
    val_mse = mean_squared_error(y_val, y_pred_val)
    test_mse = mean_squared_error(y_test, y_pred_test)
    
    results_data.append({
        "Number of Trees": n_trees,
        "Training MSE": round(train_mse, 4),
        "Validation MSE": round(val_mse, 4),
        "Test MSE": round(test_mse, 4)
    })

df_results = pd.DataFrame(results_data)
print(df_results.to_string(index=False))

 Number of Trees  Training MSE  Validation MSE  Test MSE
               2        0.0331          0.1205    0.1227
              10        0.0154          0.0930    0.0826
              25        0.0124          0.0853    0.0784
              50        0.0113          0.0822    0.0771
             100        0.0110          0.0801    0.0748
             250        0.0108          0.0793    0.0745
             500        0.0107          0.0789    0.0744
            1000        0.0107          0.0786    0.0741